### PR TITLE
Build shared and static lib with qmake

### LINKED ISSUE #13: qmake builds only shared lib
I just built the latest libxdf 0.95, and when I use qmake it builds only the shared lib. cmake works though!

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #13

### CODE REVIEW

**Comment by cbrnr** [comment]
Please let me know if this also works for you - on both my Mac and Linux machines I need these flags in order to build both static and shared libs.

It would be great if you could update the 0.95 release with all these latest changes to the build tools.

**Comment by cbrnr** [comment]
Or maybe let's make a 0.96 release since changing an existing one is difficult.

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens,

Just tested and it works very well. Let's keep it v0.95 and treat it as a 'minor bug fix'. I have already updated the windows binaries.

**Comment by cbrnr** [comment]
OK, but what happens when you download the 0.95 source? I assume you'd still get the old source. I'd really like to have these changes also in the source because my build instructions will be based on the source. Can you delete the release and make a new 0.95 with the current master?

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens,

Seems even after I deleted the v0.95 and re-release it, it will still use the old source because the name tag already exists. So I just released a v0.96.

**Comment by cbrnr** [comment]
Ok cool. You probably could delete the tag and set it to the new position, but creating 0.96 is fine.

**Pull request merged**
