### PR TITLE
Restructured sources and headers

### PR DESCRIPTION
**Pull request by cbrnr**
Maybe this fixes your crash on Windows?

### CODE REVIEW

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens. Just tested but the error persists (not in all files but in certain ones):

image

**Comment by cbrnr** [comment]
Did you configure cmake to use MinGW? You're getting a Visual C++ runtime error - this indicates that you built libxdf with vc++.

**Comment by Yida-Lin** [comment]
Hmm not sure. This is my cmake setting in Qt IDE: I thought I did select MinGW as the _CMake Generator_

image

**Comment by cbrnr** [comment]
This is really strange. Can you upload a file that crashes to our Google Drive folder?

Also, can you remove all Qt-related files from the libxdf folder and then build without any Qt stuff (i.e. don't use Qt Creator, instead use cmake and/or cmake-gui directly).

**Comment by Yida-Lin** [comment]
@cbrnr I am uploading it now. It's called `Run_A_RWEO_old01`.

I will try the CMake GUI.

**Comment by Yida-Lin** [comment]
@cbrnr I have uploaded it. It's called `Run_A_RWEO_old01`.

I am having a bit trouble with CMake GUI. Seems this dll is missing and I don't see it in my mingw/bin folder. Should I download one and copy & paste? 

image

**Comment by cbrnr** [comment]
Hm. The .dll is not in C:\MinGW\bin? Did you add this folder to the PATH variable? Some people say that it might be because something else is in your PATH that shadows the as program. Furthermore, it could also be that there's a space in the path (try putting the libxdf folder directly in C:\libxdf).

**Pull request closed without merging**
